name = "CESFunctions"
uuid = "41fc9631-8896-47d9-8244-cfbf74589b0a"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]
version = "0.2.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.9"
StaticArrays = "1"
julia = "1.8"
